### ISSUE TITLE
Many problems to run examples

### ISSUE THREAD

**Issue by ottopic** [appcelerator/hyperloop-examples#65] opened 2017-12-12 15:45 UTC
Hello,
I have downloaded hyperloop-examples. 

```
Appcelerator 5.0.0.201712081732
Titanium sdk 7.0.0.GA
CLI 7.0.0
Pod 1.3.1
Node.js 8.9.1
Xcode 9.2
iOS simulator 11.2
```

When I run the app only 5 examples works. Auto Layout, Touch Id, HTTP Request, View animation and Styled Labels. All other not. It seems not all dependency package are included.

Can you help me to configure it correctly ?

First run error:

```
[INFO] :   [Hyperloop] Generating LocalAuthentication LocalAuthentication/LocalAuthentication
2017-12-13T07:13:18.261Z | ERROR  | An uncaught exception was thrown!
ENOENT: no such file or directory, open '/Users/usernmae/Documents/Appcelerator_Studio_Workspace/hyperloop-examples/build/hyperloop/ios/js/Localytics/Localytics.js'
2017-12-13T07:13:18.262Z | ERROR  | ENOENT: no such file or directory, open '/Users/usernmae/Documents/Appcelerator_Studio_Workspace/hyperloop-examples/build/hyperloop/ios/js/Localytics/Localytics.js'
```

After second run the app start but in collection view:

```
[ERROR] :  Cannot find class with name: CollectionViewDataSourceAndDelegate
[ERROR] :  Script Error {
[ERROR] :      column = 225;
[ERROR] :      description = "Cannot find class with name: CollectionViewDataSourceAndDelegate";
[ERROR] :      line = 1;
[ERROR] :      message = "Cannot find class with name: CollectionViewDataSourceAndDelegate";
[ERROR] :      name = ClassNotFound;
[ERROR] :      nativeStack = "1   libobjc.A.dylib                     0x000000011406cf41 objc_exception_throw + 48\n2   Hyperloop_Sample                    0x000000010befc0b2 -[HyperloopClass initWithClassName:alloc:init:args:] + 386\n3   Hyperloop_Sample                    0x000000010beeec14 DefineClass + 452\n4   JavaScriptCore                      0x000000010cc523d5 _ZN3JSC19APICallbackFunction4callINS_18JSCallbackFunctionEEExPNS_9ExecStateE + 501\n5   JavaScriptCore                      0x000000010cd61cd1 _ZN3JSC5LLInt9setUpCallEPNS_9ExecStateEPNS_11InstructionENS_22CodeSpecializationKindENS_7JSValueEPNS_17LLIntCallLinkInfoE + 577\n6   JavaScriptCore                      0x000000010cd6af4d llint_entry + 27269\n7   JavaScriptCore                      0x000000010cd6af5b llint_entry + 27283\n8   JavaScriptCore                      0x000000010cd642e0 vmEntryToJavaScript + 304\n9   JavaScriptCore                      0x000000010cbf51df _ZN3JSC7JITCode7executeEPNS_2VMEPNS_14ProtoCallFrameE + 127\n10  JavaScriptCore                      0x000000010cbbb4a3 _ZN3JSC11Interpreter14executeProgramERKNS_10SourceCodeEPNS_9ExecStateEPNS_8JSObjectE + 13075\n11  JavaScriptCore                      0x000000010c908c6f _ZN3JSC8evaluateEPNS_9ExecStateERKNS_10SourceCodeENS_7JSValueERN3WTF8NakedPtrINS_9ExceptionEEE + 303\n12  JavaScriptCore                      0x000000010cc504c0 JSEvaluateScript + 432\n13  Hyperloop_Sample                    0x000000010bbc7f03 -[KrollEval jsInvokeInContext:exception:] + 259\n14  Hyperloop_Sample                    0x000000010bbc352b -[KrollBridge loadCommonJSModule:withSourceURL:] + 395\n15  Hyperloop_Sample                    0x000000010bbc4450 -[KrollBridge loadJavascriptText:fromFile:withContext:] + 96\n16  Hyperloop_Sample                    0x000000010bbc46d8 -[KrollBridge cachedLoadAsFile:asJSON:withContext:] + 264\n17  Hyperloop_Sample                    0x000000010bbc4807 -[KrollBridge loadAsFile:withContext:] + 263\n18  Hyperloop_Sample                    0x000000010bbc4b31 -[KrollBridge loadAsFileOrDirectory:withContext:] + 81\n19  Hyperloop_Sample                    0x000000010bbc558a -[KrollBridge require:path:] + 1194\n20  Hyperloop_Sample                    0x000000010bbc9cdb CommonJSRequireCallback + 187\n21  JavaScriptCore                      0x000000010cc523d5 _ZN3JSC19APICallbackFunction4callINS_18JSCallbackFunctionEEExPNS_9ExecStateE + 501\n22  JavaScriptCore                      0x000000010cd61cd1 _ZN3JSC5LLInt9setUpCallEPNS_9ExecStateEPNS_11InstructionENS_22CodeSpecializationKindENS_7JSValueEPNS_17LLIntCallLinkInfoE + 577\n23  JavaScriptCore                      0x000000010cd6af4d llint_entry + 27269\n24  JavaScriptCore                      0x000000010cd6af5b llint_entry + 27283\n25  JavaScriptCore                      0x000000010cd6b296 llint_entry + 28110\n26  JavaScriptCore                      0x000000010cd6af5b llint_entry + 27283\n27  JavaScriptCore                      0x000000010cd642e0 vmEntryToJavaScript + 304\n28  JavaScriptCore                      0x000000010cbf51df _ZN3JSC7JITCode7executeEPNS_2VMEPNS_14ProtoCallFrameE + 127\n29  JavaScriptCore                      0x000000010cbbb871 _ZN3JSC11Interpreter11executeCallEPNS_9ExecStateEPNS_8JSObjectENS_8CallTypeERKNS_8CallDataENS_7JSValueERKNS_7ArgListE + 433\n30  JavaScriptCore                      0x000000010c8ac4d2 _ZN3JSC12profiledCallEPNS_9ExecStateENS_15ProfilingReasonENS_7JSValueENS_8CallTypeERKNS_8CallDataES3_RKNS_7ArgListE + 178\n31  JavaScriptCore                      0x000000010ccb629d JSObjectCallAsFunction + 461\n32  Hyperloop_Sample                    0x000000010be179b6 __TiBindingEventProcess_block_invoke + 86\n33  Hyperloop_Sample                    0x000000010bcccddd TiThreadPerformOnMainThread + 77\n34  Hyperloop_Sample                    0x000000010be1785e TiBindingEventProcess + 1054\n35  Hyperloop_Sample                    0x000000010be17b48 -[TiBindingCallbackInvoke invoke:] + 56\n36  Hyperloop_Sample                    0x000000010bbc8dcf -[KrollContext invoke:] + 159\n37  Hyperloop_Sample                    0x000000010bbc8eaa __24-[KrollContext enqueue:]_block_invoke + 42\n38  Hyperloop_Sample                    0x000000010bcccddd TiThreadPerformOnMainThread + 77\n39  Hyperloop_Sample                    0x000000010bbc8e77 -[KrollContext enqueue:] + 135\n40  Hyperloop_Sample                    0x000000010be17baf TiBindingRunLoopEnqueue + 95\n41  Hyperloop_Sample                    0x000000010be1707e TiBindingEventFire + 334\n42  Hyperloop_Sample                    0x000000010bc8e8e0 -[TiProxy fireEvent:withObject:propagate:reportSuccess:errorCode:message:] + 208\n43  Hyperloop_Sample                    0x000000010bbf09c2 -[TiViewProxy fireEvent:withObject:propagate:reportSuccess:errorCode:message:] + 418\n44  Hyperloop_Sample                    0x000000010bc8e50b -[TiProxy fireEvent:withObject:] + 139\n45  Hyperloop_Sample                    0x000000010be444df -[TiUIListView fireClickForItemAtIndexPath:tableView:accessoryButtonTapped:] + 1359\n46  Hyperloop_Sample                    0x000000010be414a9 -[TiUIListView tableView:didSelectRowAtIndexPath:] + 73\n47  UIKit                               0x000000010e94d839 -[UITableView _selectRowAtIndexPath:animated:scrollPosition:notifyDelegate:] + 1810\n48  UIKit                               0x000000010e94da54 -[UITableView _userSelectRowAtPendingSelectionIndexPath:] + 344\n49  UIKit                               0x000000010e816d59 _runAfterCACommitDeferredBlocks + 318\n50  UIKit                               0x000000010e805bb1 _cleanUpAfterCAFlushAndRunDeferredBlocks + 280\n51  UIKit                               0x000000010e8350e0 _afterCACommitHandler + 137\n52  CoreFoundation                      0x0000000115063c07 __CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__ + 23\n53  CoreFoundation                      0x0000000115063b5e __CFRunLoopDoObservers + 430\n54  CoreFoundation                      0x0000000115048124 __CFRunLoopRun + 1572\n55  CoreFoundation                      0x0000000115047889 CFRunLoopRunSpecific + 409\n56  GraphicsServices                    0x000000011764d9c6 GSEventRunModal + 62\n57  UIKit                               0x000000010e80b5d6 UIApplicationMain + 159\n58  Hyperloop_Sample                    0x000000010bbaebd4 main + 100\n59  libdyld.dylib                       0x0000000116d94d81 start + 1\n60  ???                                 0x0000000000000001 0x0 + 1";
[ERROR] :      sourceURL = "file:///Users/username/Library/Developer/CoreSimulator/Devices/3F3BAD17-745A-45B8-86B7-5BC26FE9F620/data/Containers/Bundle/Application/EC9D22D7-9DF3-4059-88CD-FB9BA92C5A96/Hyperloop_Sample.app/subclasses/collectionviewdatasourcedelegate.js";
[ERROR] :  }
[ERROR] :  Script Error Module "subclasses/collectionviewdatasourcedelegate.js" failed to leave a valid exports object
[ERROR] :  ErrorController is up. ABORTING showing of modal controller
```

Table view example:

```
[ERROR] :  Cannot find class with name: TableViewDataSourceAndDelegate
[ERROR] :  Script Error {
[ERROR] :      column = 215;
[ERROR] :      description = "Cannot find class with name: TableViewDataSourceAndDelegate";
[ERROR] :      line = 1;
[ERROR] :      message = "Cannot find class with name: TableViewDataSourceAndDelegate";
[ERROR] :      name = ClassNotFound;
[ERROR] :      nativeStack = "1   libobjc.A.dylib                     0x000000011406cf41 objc_exception_throw + 48\n2   Hyperloop_Sample                    0x000000010befc0b2 -[HyperloopClass initWithClassName:alloc:init:args:] + 386\n3   Hyperloop_Sample                    0x000000010beeec14 DefineClass + 452\n4   JavaScriptCore                      0x000000010cc523d5 _ZN3JSC19APICallbackFunction4callINS_18JSCallbackFunctionEEExPNS_9ExecStateE + 501\n5   JavaScriptCore                      0x000000010cd61cd1 _ZN3JSC5LLInt9setUpCallEPNS_9ExecStateEPNS_11InstructionENS_22CodeSpecializationKindENS_7JSValueEPNS_17LLIntCallLinkInfoE + 577\n6   JavaScriptCore                      0x000000010cd6af4d llint_entry + 27269\n7   JavaScriptCore                      0x000000010cd6af5b llint_entry + 27283\n8   JavaScriptCore                      0x000000010cd642e0 vmEntryToJavaScript + 304\n9   JavaScriptCore                      0x000000010cbf51df _ZN3JSC7JITCode7executeEPNS_2VMEPNS_14ProtoCallFrameE + 127\n10  JavaScriptCore                      0x000000010cbbb4a3 _ZN3JSC11Interpreter14executeProgramERKNS_10SourceCodeEPNS_9ExecStateEPNS_8JSObjectE + 13075\n11  JavaScriptCore                      0x000000010c908c6f _ZN3JSC8evaluateEPNS_9ExecStateERKNS_10SourceCodeENS_7JSValueERN3WTF8NakedPtrINS_9ExceptionEEE + 303\n12  JavaScriptCore                      0x000000010cc504c0 JSEvaluateScript + 432\n13  Hyperloop_Sample                    0x000000010bbc7f03 -[KrollEval jsInvokeInContext:exception:] + 259\n14  Hyperloop_Sample                    0x000000010bbc352b -[KrollBridge loadCommonJSModule:withSourceURL:] + 395\n15  Hyperloop_Sample                    0x000000010bbc4450 -[KrollBridge loadJavascriptText:fromFile:withContext:] + 96\n16  Hyperloop_Sample                    0x000000010bbc46d8 -[KrollBridge cachedLoadAsFile:asJSON:withContext:] + 264\n17  Hyperloop_Sample                    0x000000010bbc4807 -[KrollBridge loadAsFile:withContext:] + 263\n18  Hyperloop_Sample                    0x000000010bbc4b31 -[KrollBridge loadAsFileOrDirectory:withContext:] + 81\n19  Hyperloop_Sample                    0x000000010bbc558a -[KrollBridge require:path:] + 1194\n20  Hyperloop_Sample                    0x000000010bbc9cdb CommonJSRequireCallback + 187\n21  JavaScriptCore                      0x000000010cc523d5 _ZN3JSC19APICallbackFunction4callINS_18JSCallbackFunctionEEExPNS_9ExecStateE + 501\n22  JavaScriptCore                      0x000000010cd61cd1 _ZN3JSC5LLInt9setUpCallEPNS_9ExecStateEPNS_11InstructionENS_22CodeSpecializationKindENS_7JSValueEPNS_17LLIntCallLinkInfoE + 577\n23  JavaScriptCore                      0x000000010cd6af4d llint_entry + 27269\n24  JavaScriptCore                      0x000000010cd6af5b llint_entry + 27283\n25  JavaScriptCore                      0x000000010cd6b296 llint_entry + 28110\n26  JavaScriptCore                      0x000000010cd6aee9 llint_entry + 27169\n27  JavaScriptCore                      0x000000010cd642e0 vmEntryToJavaScript + 304\n28  JavaScriptCore                      0x000000010cbf51df _ZN3JSC7JITCode7executeEPNS_2VMEPNS_14ProtoCallFrameE + 127\n29  JavaScriptCore                      0x000000010cbbb871 _ZN3JSC11Interpreter11executeCallEPNS_9ExecStateEPNS_8JSObjectENS_8CallTypeERKNS_8CallDataENS_7JSValueERKNS_7ArgListE + 433\n30  JavaScriptCore                      0x000000010c8ac4d2 _ZN3JSC12profiledCallEPNS_9ExecStateENS_15ProfilingReasonENS_7JSValueENS_8CallTypeERKNS_8CallDataES3_RKNS_7ArgListE + 178\n31  JavaScriptCore                      0x000000010ccb629d JSObjectCallAsFunction + 461\n32  Hyperloop_Sample                    0x000000010be179b6 __TiBindingEventProcess_block_invoke + 86\n33  Hyperloop_Sample                    0x000000010bcccddd TiThreadPerformOnMainThread + 77\n34  Hyperloop_Sample                    0x000000010be1785e TiBindingEventProcess + 1054\n35  Hyperloop_Sample                    0x000000010be17b48 -[TiBindingCallbackInvoke invoke:] + 56\n36  Hyperloop_Sample                    0x000000010bbc8dcf -[KrollContext invoke:] + 159\n37  Hyperloop_Sample                    0x000000010bbc8eaa __24-[KrollContext enqueue:]_block_invoke + 42\n38  Hyperloop_Sample                    0x000000010bcccddd TiThreadPerformOnMainThread + 77\n39  Hyperloop_Sample                    0x000000010bbc8e77 -[KrollContext enqueue:] + 135\n40  Hyperloop_Sample                    0x000000010be17baf TiBindingRunLoopEnqueue + 95\n41  Hyperloop_Sample                    0x000000010be1707e TiBindingEventFire + 334\n42  Hyperloop_Sample                    0x000000010bc8e8e0 -[TiProxy fireEvent:withObject:propagate:reportSuccess:errorCode:message:] + 208\n43  Hyperloop_Sample                    0x000000010bbf09c2 -[TiViewProxy fireEvent:withObject:propagate:reportSuccess:errorCode:message:] + 418\n44  Hyperloop_Sample                    0x000000010bc8e50b -[TiProxy fireEvent:withObject:] + 139\n45  Hyperloop_Sample                    0x000000010be444df -[TiUIListView fireClickForItemAtIndexPath:tableView:accessoryButtonTapped:] + 1359\n46  Hyperloop_Sample                    0x000000010be414a9 -[TiUIListView tableView:didSelectRowAtIndexPath:] + 73\n47  UIKit                               0x000000010e94d839 -[UITableView _selectRowAtIndexPath:animated:scrollPosition:notifyDelegate:] + 1810\n48  UIKit                               0x000000010e94da54 -[UITableView _userSelectRowAtPendingSelectionIndexPath:] + 344\n49  UIKit                               0x000000010e816d59 _runAfterCACommitDeferredBlocks + 318\n50  UIKit                               0x000000010e805bb1 _cleanUpAfterCAFlushAndRunDeferredBlocks + 280\n51  UIKit                               0x000000010e8350e0 _afterCACommitHandler + 137\n52  CoreFoundation                      0x0000000115063c07 __CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__ + 23\n53  CoreFoundation                      0x0000000115063b5e __CFRunLoopDoObservers + 430\n54  CoreFoundation                      0x0000000115048124 __CFRunLoopRun + 1572\n55  CoreFoundation                      0x0000000115047889 CFRunLoopRunSpecific + 409\n56  GraphicsServices                    0x000000011764d9c6 GSEventRunModal + 62\n57  UIKit                               0x000000010e80b5d6 UIApplicationMain + 159\n58  Hyperloop_Sample                    0x000000010bbaebd4 main + 100\n59  libdyld.dylib                       0x0000000116d94d81 start + 1\n60  ???                                 0x0000000000000001 0x0 + 1";
[ERROR] :      sourceURL = "file:///Users/username/Library/Developer/CoreSimulator/Devices/3F3BAD17-745A-45B8-86B7-5BC26FE9F620/data/Containers/Bundle/Application/EC9D22D7-9DF3-4059-88CD-FB9BA92C5A96/Hyperloop_Sample.app/subclasses/tableviewdatasourcedelegate.js";
[ERROR] :  }
[ERROR] :  Script Error Module "subclasses/tableviewdatasourcedelegate.js" failed to leave a valid exports object
[ERROR] :  ErrorController is up. ABORTING showing of modal controller
```

Same error for the other example.

**Comment by janvennemann** [comment] 2017-12-14 15:16
This looks like some kind of permission issue to me. On the first build it fails to generates the wrapper files which then causes the errors you see on subsequent builds. Tested it locally on my machine and everything works just fine.

Can you completely wipe your build directory and do a clean build? If that does not help try a cli build by running `rm -rf build/ && appc run -p ios` from within the `hyperloop-examples` directory.

**Comment by ottopic** [comment] 2017-12-14 18:26
I have tried but the problems are the same. First run, from terminal too, Localytics.js get error. From second build, app run but half examples won't works.

What can I do? Can I reinstall cli from command line? or node js ? or titanium sdk ? I don't know.

**Comment by janvennemann** [comment] 2017-12-15 12:58
We are tracking a similar issue over at https://jira.appcelerator.org/browse/TIMOB-25604 but still try to reproduce it on one of our machines. 

Another thing you may try in the meantime is to checkout the hyperloop-examples project to a different location. Then try to run it from CLI again. Let me know if that changes anything.

**Comment by ottopic** [comment] 2017-12-15 13:31
@janvennemann many thanks! Can you explain me where to add use_frameworks! ? I haven't understand.

**Comment by hansemannn** [comment] 2018-01-21 18:38
Glad it worked! `use_frameworks!` is the way to go for both future releases of Hyperloop and Cocoapods. Closing issue.

**Closed by hansemannn** 2018-01-21 18:38 UTC
